### ISSUE TITLE
Zenodo merging

### ISSUE THREAD

**Issue by rudygarrido** [semantic-systems/nfdi-search-engine#15]
Both question and issue.
Should Zenodo be merged with the sections Articles and Researchers? And if so how to assign properly assign them, that is 
presentation/dataset -> Article

And if they should not be merged, should a new section be created for each kind of result Zenodo returns? Like
Presentation
...

Dataset
....

Software
...

**Comment by RicardoUsbeck** [comment]
Hi, it should not be merged but get its own subsections. We will get presentations, datasets, and software repos also from other APIs in the future.

**Comment by huntila** [comment]
See #3
