### ISSUE TITLE
rdflib Graph object updated but eventually not used

### ISSUE THREAD

**Issue by patrickwestphal** [semantic-systems/nfdi-search-engine#18]
During the querying of the respective query endpoints (DBLP, Zenodo, OpenAley) an RDF graph is created and updated, but eventually not used. [This is the last line, where it is used](https://github.com/semantic-systems/nfdi-search-engine/blob/main/main.py#L19) but right the next line returns the results without doing anything with the graph. This is unfortunate, as most of the query time is spent in [the DBLP code for parsing JSON-LD to update the graph](https://github.com/semantic-systems/nfdi-search-engine/blob/main/main.py#L120) (profiler output):

```
         3188239 function calls (3012651 primitive calls) in 18.210 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       30    0.000    0.000   18.210    0.607 graph.py:1223(parse)
       30    0.008    0.000   18.202    0.607 jsonld.py:81(parse)
       30    0.000    0.000   18.189    0.606 jsonld.py:118(to_rdf)
       30    0.019    0.001   18.189    0.606 jsonld.py:146(parse)
       30    0.000    0.000   18.107    0.604 context.py:365(load)
    60/30    0.001    0.000   16.618    0.554 context.py:390(_prep_sources)
       30    0.001    0.000   16.615    0.554 context.py:430(_fetch_context)
       60    0.002    0.000   16.615    0.277 util.py:27(source_to_json)
       60    0.001    0.000   13.612    0.227 parser.py:332(create_input_source)
       30    0.000    0.000   13.611    0.454 parser.py:436(_create_input_source_from_location)
       30    0.003    0.000   13.608    0.454 parser.py:231(__init__)
  ...
```
(BTW: This is seemingly the answer to [this comment](https://github.com/semantic-systems/nfdi-search-engine/blob/main/main.py#L116))

If it is really not used, we could just remove the graph updates to improve the performance.

**Comment by RicardoUsbeck** [comment]
For now, removing it is fine but according to https://docs.google.com/presentation/d/1s7ukh7HyHgNw_ACI4q6nAmDe4C75mnwOW_axc1CWBZA/edit#slide=id.g1c7f695e1fc_0_53 we need it in the future

**Comment by RicardoUsbeck** [comment]
@huntila @Najeeb-Shams  If there is no RDF in the current dev or main branch, please close this ticket
