### ISSUE TITLE
Zenodo URI generation looks wrong

### ISSUE THREAD

**Issue by patrickwestphal** [semantic-systems/nfdi-search-engine#19]
During the extraction of basic information from the Zenodo search results [a URI is build using the `conceptrecid`attribute](https://github.com/semantic-systems/nfdi-search-engine/blob/main/main.py#L149):

```python
subject = URIRef(data['conceptrecid'])
```
However, `data['conceptrecid']` seems to be always a string containing an integer which results in a URI like this:

```python
In [1]: from rdflib import URIRef

In [2]: uri = URIRef('6857079')

In [3]: str(uri)
Out[3]: '6857079'
```

I would suggest to use other attributes for URI generation instead, e.g. `data['links']['conceptdoi']` (which would be `https://doi.org/10.5281/zenodo.6857079` for the above example) and implement a fallback strategy in case `data['links']['conceptdoi']` is not set.

**Comment by RicardoUsbeck** [comment]
+1 please do so, my bad
