### ISSUE TITLE
Return statement inside for loop

### ISSUE THREAD

**Issue by patrickwestphal** [semantic-systems/nfdi-search-engine#20]
In the [OpenAlex module](https://github.com/semantic-systems/nfdi-search-engine/blob/main/search_openalex.py#L40) there is a `return` statement inside a `for` loop which will cause to always leave the `find_authors` function after having processed the first entry of `api_response_authors`:

```python
def find_authors(oa, search_key, results):
    api_response_authors = oa.get_list_of_authors(search=search_key)
    list_of_authors = []
    for authors in api_response_authors:
        [...]

        return list_of_authors, results
```

Even though in my trials the generator `api_response_authors` always returned just one entry, the doc string of the `oa.get_list_of_authors( )` method says the return value is a generator with 'each item a dict from JSON representing a (partial) list of works'. So it seems there could be more than one entries (even though I couldn't figure out how to trigger this). Thus, I would suggest to move the `return` statement out of the loop.

**Comment by RicardoUsbeck** [comment]
What do you think @huntila ?

**Comment by huntila** [comment]
Yes, the return statement should be outside of the loop.
