### ISSUE TITLE
improve zenodo output to be more informative

### ISSUE THREAD

**Issue by RicardoUsbeck** [semantic-systems/nfdi-search-engine#3]
![image](https://user-images.githubusercontent.com/4354740/202919762-cf553e53-876a-477a-9662-c2e7ee06c50a.png)

**Comment by huntila** [comment]
<img width="1411" alt="Screenshot 2023-05-25 at 15 39 27" src="https://github.com/semantic-systems/nfdi-search-engine/assets/58974800/d08bfdea-dba9-4d20-9501-ed159ebf59d3">

**Comment by RicardoUsbeck** [comment]
Is it possible to add a description snippet to each thing?

**Comment by huntila** [comment]
![Image](https://github.com/semantic-systems/nfdi-search-engine/assets/58974800/3380d6a6-235c-458a-9e6c-33d36019c8c2)



![Image](https://github.com/semantic-systems/nfdi-search-engine/assets/58974800/6a42ea3b-6293-4e7c-b9ab-5d958c6778c4)


![Image](https://github.com/semantic-systems/nfdi-search-engine/assets/58974800/c2ef2f83-2965-401e-815b-c437345f98ce)
