### ISSUE TITLE
Integrate ELG API

### ISSUE THREAD

**Issue by huntila** [semantic-systems/nfdi-search-engine#37]
Create a feature for the nfdi-search-engine that searches over [European Language Grid](https://live.european-language-grid.eu) using it's [public API](https://european-language-grid.readthedocs.io/en/stable/all/A3_API/LTPublicAPI.html). 

Please look at [ELG documentation](https://european-language-grid.readthedocs.io/en/stable/index.html) and [ELG-Gitlab](https://gitlab.com/european-language-grid/platform/elg-platform-documentation/-/tree/9b3953811d7687246085f5976fc3be02e0dcd7e6).

**Comment by RicardoUsbeck** [comment]
Here are the steps for integrating ELG API into the nfdi-search-engine:

Familiarize yourself with the nfdi-search-engine codebase to identify the relevant files and functions that need to be modified or added to integrate ELG API.

Go through the ELG API documentation to understand its features, endpoints, and parameters.

Create a new feature in the nfdi-search-engine that specifically searches over the European Language Grid using ELG's public API.

Use the ELG API documentation to determine the necessary parameters for the search query.

Modify the nfdi-search-engine's search function to include the new feature that uses the ELG API to fetch relevant results.

Test the new feature extensively to ensure that it works as intended and does not cause any unexpected errors or issues.

Ensure that the feature is well documented in the nfdi-search-engine's documentation to make it easy for other developers to use and maintain it.

If necessary, collaborate with the ELG-Gitlab team to address any issues or concerns related to the integration of their API.

Once the feature is stable and ready for deployment, submit it for review and integration into the main nfdi-search-engine codebase.
