### ISSUE TITLE
Integrate Open Access Journals

### ISSUE THREAD

**Issue by Najeeb-Shams** [semantic-systems/nfdi-search-engine#44]
Open access journals can provide users with access to a wider range of scholarly resources.

**Comment by RicardoUsbeck** [comment]
Please describe your plan in more detail

**Comment by Najeeb-Shams** [comment]
### Here's a brief plan/steps to integrate Open Access Journals into the NFDI-Search-Engine:

**1. Defining the Integration Requirements:**
Determine the specific functionality or data we want to integrate from Open Access Journals.

**2. Explore Available APIs or Data Sources:**
Research and identify APIs or data sources that provide access to Open Access Journals.

**3. Choose an Integration Approach:**
Decide on the integration approach that best suits our needs, considering available APIs or data sources.

**4. Implement Integration:**
Add new code or modify existing code to integrate Open Access Journals into the NFDI-Search-Engine.

**5. Test Integration:**
Thoroughly test the integration to ensure it functions as expected, covering various scenarios and edge cases.

**6. Handle Authentication and Authorization:**
Implement mechanisms to handle authentication and authorization if required by the Open Access Journals API or data source.

**7. Document Integration:**
Update the documentation of the NFDI-Search-Engine to include a description or instruction of the integrated Open Access Journals (if required).

**8. Push Changes and Create Pull Request:** 
Push into a new branch in the remote repository. Create a pull request to merge the changes into the develop/main branch. Review, address feedback, and merge the pull request to update the main branch with the integrated Open Access Journals functionality.

**Comment by RicardoUsbeck** [comment]
Good plan. In general, just too broad. So maybe scale to 1-2 journals (ACM, ACL, IEEE?) to prove it is possible. My point here is, that you could endlessly do this issue but the issue should be done by 1st June.

**Comment by Najeeb-Shams** [comment]
Thank you, Ricardo. I will consider one journal according to the time restriction and proceed accordingly.

**Comment by Najeeb-Shams** [comment]
Dear Ricardo,

I have reviewed all the IEEE, ACM, ACL, and some other open-access journals. I considered various aspects such as their policies, documentation, technical support, etc. Here is a brief summary for your attention and further action.

**IEEE**: Provides API access, but in order to obtain the necessary API key, I had to submit an application. They provided the key but unfortunately, the key is still awaiting activation, despite my follow-up emails to them.

**ACM**: According to the information provided about their Digital Library, they offer different access levels to their members. However, they have not provided specific details about the API or technical/developer documentation. I have already contacted the relevant board to inquire about API access, but there has been no update thus far. It's important to note that ACM membership is not free.

**ACL**: ACL provides API access through their ACL-Anthology, which is available on GitHub. To utilize it, we need to clone the repository. This will enable us to define objects and retrieve the relevant data we require. The integration is nearly complete; it just requires some additional tracing and testing. I'm also exploring if there are any shortcuts or easier methods available.

**Comment by RicardoUsbeck** [comment]
Thanks for looking into the issue that deep. Regarding ACL, mind, that we do not index or store data as a principal of the search engine. That is, if you need to copy data instead of using the Github API, then better not touch ACL.

**Comment by RicardoUsbeck** [comment]
Isn't IEEE covered by DBLP anyway? Let's wait for that. In the meantime, please clean up unused files and comments (see backlog) or support the other ongoing tasks (see In Progress)

**Comment by Najeeb-Shams** [comment]
DBLP includes papers from IEEE, but it does not provide comprehensive coverage of all IEEE resources. For accessing IEEE's extensive collection of academic articles and publications, the primary platform is IEEE Xplore which is accessible via their APIs.
Sure I will do that.

**Comment by huntila** [comment]
IEEE is integrated.
