### ISSUE TITLE
Institutional Repositories

### ISSUE THREAD

**Issue by Najeeb-Shams** [semantic-systems/nfdi-search-engine#45]
Many universities and research institutions have their own institutional repositories that contain scholarly articles, theses, and dissertations. Adding these repositories to the nfdi-search-engine would provide users with access to a wealth of scholarly resources.

**Comment by RicardoUsbeck** [comment]
Narrow this down to 1-3 RDMs

**Comment by huntila** [comment]
@Najeeb-Shams, what is the status of this issue?

**Comment by Najeeb-Shams** [comment]
Hey @huntila the issue is still unresolved. If the team believes can improve the system's performance, we can consider integrating some useful repositories to address it.

**Comment by huntila** [comment]
Hi, can you get a list of institutions maintaining their own repositories that we can integrate with?

**Comment by Najeeb-Shams** [comment]
Dear colleagues,
Europe PMC is a pivotal repository for life sciences research, hosting an extensive collection of over 43.1 million articles, preprints, and more. Its resources are open-access and supported by robust APIs. Integrating it with our NFDI gateway is significant as it improves data accessibility, enriches cross-disciplinary research, and supports open science principles. This decision, reached after a thorough evaluation among institutional repositories, enhances the value of our gateway by offering a comprehensive and accessible source of research content for the life sciences community. If you have any feedback or suggestions you are welcome.
 
https://europepmc.org/
