### ISSUE TITLE
Integrate Research Funding Databases

### ISSUE THREAD

**Issue by Najeeb-Shams** [semantic-systems/nfdi-search-engine#47]

**Comment by RicardoUsbeck** [comment]
Important databases are GEPRIS (German) and CORDIS (EU)

**Comment by Najeeb-Shams** [comment]
Well, should we integrate one or both of them or should we explore other alternatives and then decide which ones to integrate into NFDI SE?

**Comment by RicardoUsbeck** [comment]
Well, I would integrate exactly these two since they are most important. 

In general, issues should be very concrete to be able to assess whether a ticket can be done in a given time frame.

**Comment by Najeeb-Shams** [comment]
Hi Ricardo, CORDIS is integrated, but GEPRIS currently only provides HTML data. What do you suggest?

**Comment by RicardoUsbeck** [comment]
It looks like the GEPRIS HTML is parseable. Have you tried Beatufil Soup plus XQuery/XPath ?

**Comment by Najeeb-Shams** [comment]
I haven't yet tried using Beautiful Soup with XQuery or XPath, I will try.

**Comment by huntila** [comment]
Both GEPRIS (German) and CORDIS (EU) are integrated.
