### ISSUE TITLE
Increase speed of rendering

### ISSUE THREAD

**Issue by RicardoUsbeck** [semantic-systems/nfdi-search-engine#6]
The main branch is currently very slow (ca. 15s) per result. Increase speed

**Comment by RicardoUsbeck** [comment]
@huntila @Najeeb-Shams can that be closed?

**Comment by Najeeb-Shams** [comment]
I guess yes.

**Comment by RicardoUsbeck** [comment]
Okay, please mention in the PR this issue to close it
