### ISSUE TITLE
Logging Issues

### ISSUE THREAD

**Issue by RicardoUsbeck** [semantic-systems/nfdi-search-engine#66]
┆Issue is synchronized with this [Trello card](https://trello.com/c/yTJVrMbf) by [Unito](https://www.unito.io)

**Comment by patrickwestphal** [comment]
What's the issue here?

**Comment by RicardoUsbeck** [comment]
That it is currently deactivated everywhere afaik. @janreineke and @huntila and @Najeeb-Shams can tell more

**Comment by janreineke** [comment]
This issue was opened because you (@patrickwestphal) mentioned in another comment somewhere else:
> The logging was stripped down to console logging at the moment and cannot be configured via a logging config anymore (as of 2023-06-01) as someone removed this.

**Comment by RicardoUsbeck** [comment]
I also want to track how many users are there and what they are looking for. Anonymous of course
