### ISSUE TITLE
Link resources together

### ISSUE THREAD

**Issue by RicardoUsbeck** [semantic-systems/nfdi-search-engine#7]
If I get me as an author of Zenodo and me from DBLP, it should be showed as one item. 

Thus, link them by URL or ORCID. Same for papers

**Comment by rudygarrido** [comment]
DBLP and OpenAlex duplicates have been merged. The hyperlink is assigned to the first result found. Zenodo is still shown as independent results, it should be merged and will handle duplicates then.

Screenshots to show how it behaves and will close the issue with positive feedback.

![imagen](https://user-images.githubusercontent.com/13245994/210770141-d3f6d125-0099-4b80-98a0-5c5c7e7eabcc.png)
![imagen](https://user-images.githubusercontent.com/13245994/210770876-9e7edd4f-1edf-4fcd-83ef-ee139db24eab.png)
