### ISSUE TITLE
Integrate NFDI badge

### ISSUE THREAD

**Issue by RicardoUsbeck** [semantic-systems/nfdi-search-engine#8]
see e.g. https://orkg.org/

Github repo: https://gitlab.com/TIBHannover/nfdi4ds/nfdi4ds-widget/-/tree/main

HTML snippet: https://tibhannover.gitlab.io/nfdi4ds/nfdi4ds-widget/

**Comment by huntila** [comment]
Done!

**Comment by RicardoUsbeck** [comment]
@huntila you can also connect the issues to branches https://github.com/semantic-systems/nfdi-search-engine/tree/nfdi-se-najeeb, PR #50 or issues
